### ISSUE TITLE
CSS bug. Top menu gets white text on a white background

### ISSUE THREAD

**Issue by harry-wood** [amcaplan/emea-on-rails#4]
A CSS bug. The top menu gets white text on a white background at certain screen widths.

![animation](https://user-images.githubusercontent.com/227525/121256255-430c3f80-c8a4-11eb-8213-c0efeca01f30.gif)

Luckily you can still see the text by mousing over, but definitely a bug.

This happens with screen widths greater than about 770 pixels, but less than 1024 pixels.

**Comment by bkmgit** [comment]
Thanks for reporting this.

**Comment by amcaplan** [comment]
Thanks for the report! I've pushed a fix.
